fix: pipelines ignore changes when versioning files

diff --git a/.github/workflows/dev-ci-cd.yaml b/.github/workflows/dev-ci-cd.yaml
--- a/.github/workflows/dev-ci-cd.yaml
+++ b/.github/workflows/dev-ci-cd.yaml
@@ -17,24 +17,41 @@ jobs:
     runs-on: ubuntu-latest
 
     outputs:
-      version: ${{ steps.ver.outputs.version }}
+      base_version: ${{ steps.ver.outputs.base_version }}
+      beta_version: ${{ steps.ver.outputs.beta_version }}
+      full_version: ${{ steps.ver.outputs.full_version }}
 
     steps:
       - uses: actions/checkout@v4
 
-      - name: Read version
+      - name: Read version + beta bump
         id: ver
         run: |
           set -euo pipefail
 
-          VERSION=$(tr -d '\n' < VERSION)
+          BASE=$(tr -d '\n' < VERSION)
 
-          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "::error::VERSION must be semantic version like 1.2.3"
+          if ! [[ "$BASE" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "::error::VERSION must be 1.2.3"
             exit 1
           fi
 
-          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
+          BETA_FILE="BETA"
+
+          if [ ! -f "$BETA_FILE" ]; then
+            echo "0" > "$BETA_FILE"
+          fi
+
+          BETA=$(cat "$BETA_FILE")
+          BETA=$((BETA + 1))
+
+          echo "$BETA" > "$BETA_FILE"
+
+          FULL="${BASE}beta${BETA}"
+
+          echo "base_version=$BASE" >> "$GITHUB_OUTPUT"
+          echo "beta_version=$BETA" >> "$GITHUB_OUTPUT"
+          echo "full_version=$FULL" >> "$GITHUB_OUTPUT"
 
   # ---------------------------------------------------
   # 2. DOCKER IMAGE (GHA CACHE ONLY)
@@ -147,10 +164,14 @@ jobs:
     runs-on: ubuntu-latest
     needs: versioning
     env:
-      VERSION: ${{ needs.versioning.outputs.version }}
+      VERSION: ${{ needs.versioning.outputs.full_version }}
     
     steps:
       - uses: actions/checkout@v4
+
+      - name: Prevent CI file pollution
+        run: |
+          git update-index --assume-unchanged amxmodx/scripting/include/discordapiconsts.inc
 
       - name: Patch versioned include for discordapiconsts.inc
         run: |
@@ -218,7 +239,7 @@ jobs:
     runs-on: ubuntu-latest
     needs: [libs-build, compile-amxx-plugins, versioning]
     env:
-      VERSION: ${{ needs.versioning.outputs.version }}
+      VERSION: ${{ needs.versioning.outputs.full_version }}
 
     strategy:
       matrix:
@@ -236,6 +257,10 @@ jobs:
       - uses: actions/checkout@v4
         with:
           ref: ${{ github.ref }}
+
+      - name: Prevent CI file pollution
+        run: |
+          git update-index --assume-unchanged vendor/include/amxmodx/sdk/moduleconfig.h
 
       - name: Inject module version
         run: |
